# Generated by Django 3.1.1 on 2020-10-15 07:12

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='overview',
            field=tinymce.models.HTMLField(default='hcdkjh'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=tinymce.models.HTMLField(default='jkrfg'),
            preserve_default=False,
        ),
    ]
